version: '3'
services:
  node:
    container_name: url-shortener
    image: node:12
    working_dir: app
    restart: always
    build: .
    ports:
      - '8080:3000'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'